title: AISAY - AI Document Parser
url: https://www.aisay.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#6031b6"
  secondary-color: "#4372d6"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: AISAY processes your documents, extracts facts and cross-checks
  information. It takes care of the trivial so you can focus on what's
  important.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d2ljppup9e8lke.amplifyapp.com
prod: https://master.d2mtve6cyiufzy.amplifyapp.com
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
